services:
  naming-server:
    build:
      context: ./naming-server
    container_name: naming-server
    ports:
      - "8761:8761"

  user-service:
    build:
      context: ./user-service
    depends_on:
      - db
      - naming-server
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=user-db
      - DB_USER=admin
      - DB_PASSWORD=secret
    ports:
      - "8081:8081"

  learning-service:
    build:
      context: ./learning-service
    depends_on:
      - db
      - naming-server
    environment:
      - SPRING_APPLICATION_NAME=learning-service
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=learning-db
      - DB_USER=admin
      - DB_PASSWORD=secret

  db:
    image: postgres:16
    container_name: learning-db
    restart: always
    environment:
      POSTGRES_DB: learning-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
